version: "3"
services:
  backend:
    container_name: backend    
    build: ./backend
    working_dir: /usr/src/app
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8080"
    ports:
      - 8080:8080
  frontend:
    build: ./frontend/
    container_name: frontend
    working_dir: /usr/src/app    
    command: bash -c "yarn start"
    environment:
      - PORT=3000    
    ports:
      - 3000:3000
