version: "3"
services:
  frontend:
    build: ./frontend/
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app    
    command: bash -c "yarn start "
    environment:
      - PORT=3000    
    ports:
      - 3000:3000
  backend:
    container_name: backend    
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./backend/app:/usr/src/app            
  db:
    image: postgres:13-alpine
    container_name: backend-db    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
volumes:
  postgres_data:
